### ISSUE TITLE
problem when run build and start

### ISSUE THREAD

**Issue by Kiris-tingna** [Raincal/smms#5]
```
\webpack\lib\Chunk.js:245
                        const idx = block.chunks.indexOf(this);
                                                ^

TypeError: Cannot read property 'indexOf' of null
    at blocks.forEach.block (G:\Kiristingna\node-smms\node_modules\webpack\lib\Chunk.js:245:28)
    at Array.forEach (native)
    at Chunk.remove (G:\Kiristingna\node-smms\node_modules\webpack\lib\Chunk.js:244:15)
    at chunks.filter.forEach (G:\Kiristingna\node-smms\node_modules\webpack\lib\optimize\RemoveEmptyChunksPlugin.js:14:13)
    at Array.forEach (native)
    at Compilation.compilation.plugin (G:\Kiristingna\node-smms\node_modules\webpack\lib\optimize\RemoveEmptyChunksPlugin.js:13:7)
    at Compilation.applyPluginsBailResult1 (G:\Kiristingna\node-smms\node_modules\tapable\lib\Tapable.js:140:27)
    at Compilation.seal (G:\Kiristingna\node-smms\node_modules\webpack\lib\Compilation.js:598:14)
    at applyPluginsParallel.err (G:\Kiristingna\node-smms\node_modules\webpack\lib\Compiler.js:508:17)
    at G:\Kiristingna\node-smms\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (G:\Kiristingna\node-smms\node_modules\webpack\lib\Compilation.js:505:11)
    at processModuleDependencies.err (G:\Kiristingna\node-smms\node_modules\webpack\lib\Compilation.js:475:14)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Kiris-tingna** [comment]
- node v7.2.1
- npm  v3.10.10

**Comment by Kiris-tingna** [comment]
just run git clone and npm install

**Comment by Raincal** [comment]
@Kiris-tingna 用yarn安装依赖 npm没有锁定版本号

**Comment by Kiris-tingna** [comment]
`ok` 已解决

另外 lz能给个nginx配置的代码么 proxy那块

**Comment by Raincal** [comment]
@Kiris-tingna 更新添加了nginx配置 你可以看下

**Comment by Kiris-tingna** [comment]
# finished
- need add `open-ssl` configure
- sudo make && sudo make install
